import { LOGIN_ROLE } from "@/shared/constants";
import { PRIVATE_ROUTES, PUBLIC_ROUTES } from "@/shared/routes";

export type RoleKey = LOGIN_ROLE;

const adminRoutes = [
  PRIVATE_ROUTES.DASHBOARD,
  PRIVATE_ROUTES.DASHBOARD_ANALYTICS,
  PRIVATE_ROUTES.PROPERTIES,
  PRIVATE_ROUTES.PROPERTIES_LIST,
  PRIVATE_ROUTES.PROPERTIES_DISAPPROVED,
  PRIVATE_ROUTES.PROPERTIES_ASSETS,
  PRIVATE_ROUTES.PROPERTIES_ORGANISATIONS,
  PRIVATE_ROUTES.ORGANISATIONS,
  PRIVATE_ROUTES.ORGANISATIONS_PROPERTIES,
  PRIVATE_ROUTES.USERS,
  PRIVATE_ROUTES.USERS_LIST,
  PRIVATE_ROUTES.TRANSACTIONS_LIST,
  PRIVATE_ROUTES.TOKEN_REQUESTS_LIST,
  PRIVATE_ROUTES.KYC,
  PRIVATE_ROUTES.KYC_PENDING,
  PRIVATE_ROUTES.BROADCAST_MESSAGES,
  PRIVATE_ROUTES.BROADCAST_MESSAGES_LIST,
  PRIVATE_ROUTES.BROADCAST_MESSAGES_VIEW,
] as const;

const orgRoutes = [PRIVATE_ROUTES.ORGANISATIONS_PROPERTIES] as const;

export const allowedRoutes: Record<RoleKey, readonly string[]> = {
  [LOGIN_ROLE.ADMIN]: adminRoutes,
  [LOGIN_ROLE.ORGANISATION]: orgRoutes,
};

export const fallbackRouteByRole: Record<RoleKey, string> = {
  [LOGIN_ROLE.ADMIN]: PRIVATE_ROUTES.DASHBOARD_ANALYTICS,
  [LOGIN_ROLE.ORGANISATION]: PRIVATE_ROUTES.ORGANISATIONS_PROPERTIES,
};

export const publicRoutes = Object.values(PUBLIC_ROUTES);
export const protectedRoutes = Object.values(PRIVATE_ROUTES);
