export const PUBLIC_ROUTES = {
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
};

export const PRIVATE_ROUTES = {
  DASHBOARD: "/dashboard",
  PROPERTIES: "/properties",
  PROPERTIES_LIST: "/properties",
  PROPERTIES_DISAPPROVED: "/properties/disapproved",
  PROPERTIES_ASSETS: "/properties/assets",
  PROPERTIES_ORGANISATIONS: "/properties/organisations",
  ORGANISATIONS: "/organisations",
  ORGANISATIONS_PROPERTIES: "/organisations/properties",
  PODCASTS: "/podcasts",
  PODCASTS_LIST: "/podcasts/list",
  USERS: "/users",
  USERS_LIST: "/users/list",
  USERS_REPORTED: "/users/reported",
  USERS_SPOTLIGHTED: "/users/spotlighted",
  VIDEOS: "/videos",
  VIDEOS_LIST: "/videos/list",
  USERS_VIEW: "/users/view",
  DASHBOARD_CRM: "/dashboard/crm",
  INVOICES_LIST: "/invoices/list",
  INVOICES_PREVIEW: "/invoices/preview",
  INVOICES_ADD: "/invoices/add",
  INVOICES_EDIT: "/invoices/edit",
  DASHBOARD_ANALYTICS: "/dashboard/analytics",
  USERS_VIEW_ACCOUNT: "/users/view/account",
  USERS_VIEW_SECURITY: "/users/view/security",
  USERS_VIEW_BILLING: "/users/view/billing",
  USERS_VIEW_NOTIFICATIONS: "/users/view/notifications",
  USERS_VIEW_CONNECTIONS: "/users/view/connections",
  USERS_VIEW_EVENTS: "/users/view/events",
  USERS_VIEW_COMPANIES: "/users/view/companies",
  USERS_VIEW_GROUPS: "/users/view/groups",
  TRANSACTIONS_LIST: "/transactions/list",
  SUBSCRIPTIONS_LIST: "/subscriptions/list",
  SUBSCRIPTIONS_VIEW: "/subscriptions/view",
  BADGES: "/badges",
  BADGES_LIST: "/badges/list",
  BADGES_ADD: "/badges/add",
  BADGES_EDIT: "/badges/edit",
  COMPANIES: "/companies",
  COMPANIES_LIST: "/companies/list",
  COMPANIES_VIEW: "/companies/view",
  COMPANIES_VIEW_JOBS: "/companies/view/jobs",
  COMPANIES_VIEW_EVENTS: "/companies/view/events",
  COMPANIES_VIEW_BUSINESS: "/companies/view/businessleads",
  COMPANIES_VIEW_HIRING: "/companies/view/hiring",
  COMPANIES_VIEW_ENGAGEMENT: "/companies/view/engagement",
  COMPANIES_VIEW_SPONSORSHIP: "/companies/view/sponsorship",
  COMPANIES_VIEW_BOOST: "/companies/view/boost",
  COMPANIES_VIEW_GROWTH: "/companies/view/companygrowth",
  PROMO_CODES_LIST: "/promo-codes/list",
  EVENTS_LIST: "/events/list",
  GROUPS_LIST: "/groups/list",
  GROUPS_INACTIVE: "/groups/inactive",
  GROUPS_VIEW: "/groups/view",
  PLANS_LIST: "/plans/list",
  POSTS_LIST: "/posts/list",
  GAME_CONFIGS: "/game-configs",
  GAME_CONFIGS_LIST: "/game-configs/list",
  GAME_CONFIGS_VIEW: "/game-configs/view",
  BETS_HISTORY: "/bets-history",
  BETS_HISTORY_LIST: "/bets-history/list",
  CONFIGS: "/configs",
  CONFIGS_LIST: "/configs/list",
  CONFIGS_POINT_RULES: "/configs/point-rules",
  CONFIGS_DEFAULT_FEATURES: "/configs/default-features",
  CHAT: "/chat",
  CHAT_ROOMS_LIST: "/chat/rooms/list",
  CHAT_MESSAGES: "/chat/messages",
  CHAT_LIVE: "/chat/live",

  // Broadcast Messages
  BROADCAST_MESSAGES: "/broadcast-messages",
  BROADCAST_MESSAGES_LIST: "/broadcast-messages/list",
  BROADCAST_MESSAGES_VIEW: "/broadcast-messages/view",

  // Token Requests
  TOKEN_REQUESTS_LIST: "/tokens/requests",

  // KYC — identity claim requests (all statuses)
  KYC_VERIFICATION: "/kyc/verification",
  /** Legacy path; redirects to KYC_VERIFICATION */
  KYC_PENDING: "/kyc/pending",

  // Roles
  ROLES: "/roles",
  ROLES_LIST: "/roles/list",
  ROLES_VIEW: "/roles/view",

  // Bonus Slides
  BONUS_SLIDES: "/bonus-slides",
  BONUS_SLIDES_LIST: "/bonus-slides/list",
  BONUS_SLIDES_ADD: "/bonus-slides/add",
  BONUS_SLIDES_EDIT: "/bonus-slides/edit",
};
export const ROUTES = {
  ...PUBLIC_ROUTES,
  ...PRIVATE_ROUTES,
};
